services:
  # 数据库
  mariadb:
    image: mariadb:11.8.2-ubi9
    environment:
      - MARIADB_ROOT_PASSWORD=Goodnewchat
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=Goodnewchat
      - MARIADB_DATABASE=niuchat
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - niuchat_mariadb_data:/var/lib/mysql
    networks:
      - niuchat_network

  # 消息队列
  rabbitmq:
    image: bitnami/rabbitmq:4.1.2
    environment:
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=bitnami
    # ports:
    #   - "5672:5672"
    #   - "15672:15672"
    networks:
      - niuchat_network

  # 对话socket.io服务
  niuchat_ws:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_USER=root
      - DB_PASSWORD=Goodnewchat
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_NAME=niuchat
      # - LLM_API_KEY=sk-jwcnjpikvwlvkqaodhmtqallesmqoxakvfpigazqdjfqkyxo
      # - LLM_BASE_URL=https://api.siliconflow.cn/v1
      # - LLM_MODEL_NAME=Qwen/Qwen3-32B
      - LLM_API_KEY=ollama
      - LLM_BASE_URL=http://192.168.0.5:11434/v1
      - LLM_MODEL_NAME=qwen2.5
      - EMBEDDING_API_KEY=ollama
      - EMBEDDING_BASE_URL=http://192.168.0.5:11434/v1
      - EMBEDDING_MODEL_NAME=bge-m3
      - RABBITMQ_URL=amqp://user:bitnami@rabbitmq:5672/
    restart: unless-stopped
    volumes:
      - ./milvus_db:/app/milvus_db/
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
      - rabbitmq
    networks:
      - niuchat_network

# 网桥
networks:
  niuchat_network:
    driver: bridge

# 数据卷
volumes:
  niuchat_mariadb_data:
    driver: local
